# trying to compare data generated by core vs sean generated counts

sean <- read_csv('data/processed/vst_seancounts.csv')
bmc <- read_csv('data/processed/deseq_varstabilized_data.csv')


sean_matrix <- sean |> 
  mutate(tdd = str_c(timepoint, donor, drug, sep = "_")) |>
  as.data.frame() |>
  column_to_rownames('tdd') |>
  dplyr::select(`A1BG-AS1`:ZZZ3) |>
  t()

gene_variances_sean <- apply(sean_matrix, 1, var)
  apply(, 1, var) 

# if we keep only genes with variance > 0.05, how many is that.

# 400! a lovely number. 
hvgs_sean <- rownames(sean_matrix)[gene_variances_sean > 0.1]

hvg_counts <- assay(vsd)|> 
  as.data.frame() |>
  rownames_to_column('ensembl_id') |>
  filter(ensembl_id %in% names(hvgs)) |>
  left_join(only96 |> select(!counts)) |>
  column_to_rownames('gene') |>
  select(!ensembl_id)


hvg_counts_forPCA <- t(hvg_counts) |>
  as.data.frame() 

girl <- coldata |> 
      select(donor, drug_broad) |>
      as.data.frame(row.names = rownames(coldata))

rownames(girl) <- rownames(coldata)

pheatmap::pheatmap(hvgs_sean, 
    annotation_col = girl
)
